"""modifying user table

Revision ID: 067fcf19418e
Revises: a93f080c8c54
Create Date: 2025-08-21 14:23:15.044149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067fcf19418e'
down_revision = 'a93f080c8c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_color', sa.String(length=7), nullable=True))
        batch_op.drop_column('avatar_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
        batch_op.drop_column('icon_color')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
