"""empty message

Revision ID: 331eee82cac9
Revises: 8bc0050aa2e2
Create Date: 2025-07-03 17:38:02.892253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331eee82cac9'
down_revision = '8bc0050aa2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###
