"""add soft delete to tasks

Revision ID: 3dc72fcd2321
Revises: 067fcf19418e
Create Date: 2025-09-15 14:04:50.336574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc72fcd2321'
down_revision = '067fcf19418e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['deleted_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_deleted_at'))
        batch_op.drop_column('deleted_by_user_id')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
