"""modifying user table

Revision ID: a93f080c8c54
Revises: 
Create Date: 2025-08-20 17:24:24.656606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93f080c8c54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('profile_icon_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_icon_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('avatar_color')

    # ### end Alembic commands ###
