"""adding archive tables

Revision ID: ae8c355d3099
Revises: 3dc72fcd2321
Create Date: 2025-09-17 13:43:26.235235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8c355d3099'
down_revision = '3dc72fcd2321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('archived_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['archived_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_completed_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_archived_at'))
        batch_op.drop_column('archived_by_user_id')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
