"""Add new fields to Task model

Revision ID: d5ada34a7669
Revises: 
Create Date: 2025-06-26 00:33:50.529730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5ada34a7669'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prioridade', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('categoria', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status_inicial', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tempo_estimado', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tempo_unidade', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('relacionado_a', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('lembretes', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('anexos', postgresql.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('anexos')
        batch_op.drop_column('tags')
        batch_op.drop_column('lembretes')
        batch_op.drop_column('relacionado_a')
        batch_op.drop_column('tempo_unidade')
        batch_op.drop_column('tempo_estimado')
        batch_op.drop_column('status_inicial')
        batch_op.drop_column('categoria')
        batch_op.drop_column('prioridade')

    # ### end Alembic commands ###
